export const defaultCategories = [
  {
    _id: 'default-1',
    name: 'Salary',
    mainCategory: 'income',
    isDefault: true,
    icon: 'DollarSign',
    color: '#5F27CD',
  },
  {
    _id: 'default-2',
    name: 'Business',
    mainCategory: 'income',
    isDefault: true,
    icon: 'Briefcase',
    color: '#00D2D3',
  },
  {
    _id: 'default-3',
    name: 'Gift',
    mainCategory: 'income',
    isDefault: true,
    icon: 'Gift',
    color: '#26DE81',
  },
  {
    _id: 'default-4',
    name: 'Housing & Utilities',
    mainCategory: 'essentials',
    isDefault: true,
    icon: 'Home',
    color: '#FF6B6B',
  },
  {
    _id: 'default-5',
    name: 'Food & Groceries',
    mainCategory: 'essentials',
    isDefault: true,
    icon: 'ShoppingCart',
    color: '#96CEB4',
  },
  {
    _id: 'default-6',
    name: 'Transportation',
    mainCategory: 'essentials',
    isDefault: true,
    icon: 'Car',
    color: '#54A0FF',
  },
  {
    _id: 'default-7',
    name: 'Personal & Health',
    mainCategory: 'essentials',
    isDefault: true,
    icon: 'Heart',
    color: '#FF9FF3',
  },
  {
    _id: 'default-8',
    name: 'Loan EMI',
    mainCategory: 'commitments',
    isDefault: true,
    icon: 'CreditCard',
    color: '#FECA57',
  },
  {
    _id: 'default-9',
    name: 'Insurance',
    mainCategory: 'commitments',
    isDefault: true,
    icon: 'Shield',
    color: '#A55EEA',
  },
  {
    _id: 'default-10',
    name: 'Subscriptions',
    mainCategory: 'commitments',
    isDefault: true,
    icon: 'FileText',
    color: '#4ECDC4',
  },
  {
    _id: 'default-11',
    name: 'Emergency Fund',
    mainCategory: 'savings',
    isDefault: true,
    icon: 'Piggybank',
    color: '#45B7D1',
  },
  {
    _id: 'default-12',
    name: 'Investment',
    mainCategory: 'savings',
    isDefault: true,
    icon: 'TrendingUp',
    color: '#26DE81',
  },
];
