export type CategoryType = 'income' | 'essential' | 'commitment' | 'saving';

export interface TransactionData {
  // Core fields
  categoryType: CategoryType;               // Main category type
  subCategory: string;                      // Final subcategory (could be selected or custom)
  category: string;                         // Dropdown selection (e.g., 'Other' or a predefined name)
  customCategory?: string;                  // If 'category' is 'Other', this holds the typed custom name
  amount: number;                           // Amount spent or earned
  description: string;                      // Notes or description
  date: string;                             // Date in ISO format (e.g., "2025-07-21")

  // Optional backend-handled values (not required in form input, but may exist in stored data)
  userId?: string;                          // Set by backend
  familyId?: string;                        // Set by backend
  createdAt?: Date;                         // Auto-generated by backend
}